category: Game
description: Rattletrap parses and generates Rocket League replays.
executables:
  rattletrap:
    dependencies:
    - base
    - rattletrap
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executables
extra-source-files:
- CHANGELOG.markdown
- replays/*.replay
- package.yaml
- README.markdown
- stack.yaml
ghc-options: -Wall
github: tfausak/rattletrap
library:
  default-extensions:
  - Strict
  dependencies:
  - aeson >=0.11 && <1.3
  - aeson-casing >=0.1 && <0.2
  - base >=4.9 && <4.10
  - bimap >=0.3 && <0.4
  - binary >=0.8 && <0.9
  - binary-bits >=0.5 && <0.6
  - bytestring >=0.10 && <0.11
  - containers >=0.5 && <0.6
  - data-binary-ieee754 >=0.4 && <0.5
  - template-haskell >=2.11 && <2.12
  - text >=1.2 && <1.3
  - vector >=0.11 && <0.13
  other-modules: Paths_rattletrap
  source-dirs: library
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
name: rattletrap
synopsis: Parse and generate Rocket League replays.
tests:
  test:
    dependencies:
    - base
    - bytestring
    - filepath >=1.4 && <1.5
    - hspec >=2.4 && <2.5
    - rattletrap
    - temporary >=1.2 && <1.3
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: tests
version: '2.4.0'
