name: rattletrap
version: 2.5.0

category: Game
description: Rattletrap parses and generates Rocket League replays.
extra-source-files:
  - CHANGELOG.markdown
  - replays/*.replay
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/rattletrap
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Parse and generate Rocket League replays.

dependencies:
  - aeson >= 1.2.1 && < 1.3
  - base >= 4.10.0 && < 4.11
  - bimap >= 0.3.3 && < 0.4
  - binary >= 0.8.5 && < 0.9
  - binary-bits >= 0.5 && < 0.6
  - bytestring >= 0.10.8 && < 0.11
  - containers >= 0.5.10 && < 0.6
  - data-binary-ieee754 >= 0.4.4 && < 0.5
  - template-haskell >= 2.12.0 && < 2.13
  - text >= 1.2.2 && < 1.3
  - vector >= 0.12.0 && < 0.13
ghc-options: -Wall

library:
  default-extensions:
    - Strict
  other-modules: Paths_rattletrap
  source-dirs: library

executables:
  rattletrap:
    dependencies:
      - rattletrap
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executables

tests:
  test:
    dependencies:
      - filepath >= 1.4.1 && < 1.5
      - hspec >= 2.4.4 && < 2.5
      - rattletrap
      - temporary >= 1.2.1 && < 1.3
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    main: Main.hs
    source-dirs: tests
