name: rattletrap
version: 4.1.0

category: Game
description: Rattletrap parses and generates Rocket League replays.
extra-source-files:
  - CHANGELOG.markdown
  - package.yaml
  - README.markdown
  - stack.yaml
github: tfausak/rattletrap
license-file: LICENSE.markdown
license: MIT
maintainer: Taylor Fausak
synopsis: Parse and generate Rocket League replays.

dependencies:
  aeson-pretty: '>= 0.8.5 && < 0.9'
  aeson: '>= 1.2.4 && < 1.5'
  base: '>= 4.10.1 && < 4.12'
  binary-bits: '>= 0.5 && < 0.6'
  binary: '>= 0.8.5 && < 0.9'
  bytestring: '>= 0.10.8 && < 0.11'
  containers: '>= 0.5.10 && < 0.6'
  filepath: '>= 1.4.1 && < 1.5'
  http-client-tls: '>= 0.3.5 && < 0.4'
  http-client: '>= 0.5.10 && < 0.6'
  template-haskell: '>= 2.12.0 && < 2.14'
  text: '>= 1.2.3 && < 1.3'
  transformers: '>= 0.5.2 && < 0.6'
ghc-options:
  - -optP -Wno-nonportable-include-path # https://github.com/haskell/cabal/issues/4739
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-import-lists
  - -Wno-safe
  - -Wno-unsafe

library:
  source-dirs: library

executable:
  dependencies: rattletrap
  ghc-options:
    - -rtsopts
    - -threaded
  main: Main.hs
  source-dirs: executables

tests:
  test:
    dependencies:
      HUnit: '>= 1.6.0 && < 1.7'
      rattletrap: -any
      temporary: '>= 1.2.1 && < 1.4'
    ghc-options:
      - -rtsopts
      - -threaded
    main: Main.hs
    source-dirs: tests
