{
  "services": {
    "devcontainer": {
      "command": "sh -exc 'sleep infinity'",
      "image": "public.ecr.aws/acilearning/haskell:9.6.2",
      "init": true,
      "volumes": [
        "..:/workspaces/rattletrap",
        "./volumes/cabal/cache:/home/vscode/.cache/cabal",
        "./volumes/cabal/state:/home/vscode/.local/state/cabal"
      ],
      "working_dir": "/workspaces/rattletrap"
    }
  }
}
