jobs:
  build:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: mkdir artifact
      - id: haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - run: ghc-pkg list
      - run: cabal sdist --output-dir artifact
      - run: cabal configure --enable-optimization=2 --enable-tests --flags=pedantic --jobs
      - run: cat cabal.project.local
      - run: cp cabal.project.local artifact
      - run: cabal freeze
      - run: cat cabal.project.freeze
      - run: cp cabal.project.freeze artifact
      - run: cabal outdated --v2-freeze-file
      - uses: actions/cache@v4
        with:
          key: ${{ matrix.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          path: ${{ steps.haskell.outputs.cabal-store }}
          restore-keys: ${{ matrix.os }}-${{ matrix.ghc }}-
      - run: cabal build --only-download
      - run: cabal build --only-dependencies
      - run: cabal build
      - run: cp $( cabal list-bin rattletrap ) artifact
      - run: cabal run -- rattletrap --schema --output=artifact/schema.json
      - run: tar --create --file artifact.tar --verbose artifact
      - uses: actions/upload-artifact@v4
        with:
          name: rattletrap-${{ github.sha }}-ghc-${{ matrix.ghc }}-${{ matrix.os }}
          path: artifact.tar
      - run: cabal run -- rattletrap-test-suite
      - run: npm install ajv-cli
      - run: runghc src/util/check-schema.hs
    strategy:
      matrix:
        include:
          - ghc: '9.10'
            os: macos-13
          - ghc: '9.10'
            os: macos-14
          - ghc: 9.6
            os: ubuntu-22.04
          - ghc: 9.8
            os: ubuntu-22.04
          - ghc: '9.10'
            os: ubuntu-22.04
          - ghc: '9.10'
            os: windows-2022
  cabal:
    name: Cabal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cabal check
  gild:
    name: Gild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tfausak/cabal-gild-setup-action@v2
      - run: cabal-gild --input rattletrap.cabal --mode check
  hlint:
    name: HLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/hlint-setup@285e006d7b88f4da9371b8180829507d42d43756
      - uses: haskell-actions/hlint-run@v2
        with:
          fail-on: status
  ormolu:
    name: Ormolu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/run-ormolu@v15
  release:
    env:
      PREFIX: rattletrap-${{ github.event.release.tag_name }}
    if: ${{ github.event_name == 'release' }}
    name: Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - run: sh -exc 'for d in *; do cd $d; tar --extract --file artifact.tar --verbose; cd ..; done'
      - run: cp rattletrap-${{ github.sha }}-ghc-9.10-ubuntu-22.04/artifact/${{ env.PREFIX }}.tar.gz .
      - run: cp rattletrap-${{ github.sha }}-ghc-9.10-ubuntu-22.04/artifact/schema.json ${{ env.PREFIX }}-schema.json
      - run: tar --auto-compress --create --file ../../${{ env.PREFIX }}-darwin-x64.tar.gz --verbose rattletrap
        working-directory: rattletrap-${{ github.sha }}-ghc-9.10-macos-13/artifact
      - run: tar --auto-compress --create --file ../../${{ env.PREFIX }}-darwin-arm64.tar.gz --verbose rattletrap
        working-directory: rattletrap-${{ github.sha }}-ghc-9.10-macos-14/artifact
      - run: tar --auto-compress --create --file ../../${{ env.PREFIX }}-linux-x64.tar.gz --verbose rattletrap
        working-directory: rattletrap-${{ github.sha }}-ghc-9.10-ubuntu-22.04/artifact
      - run: tar --auto-compress --create --file ../../${{ env.PREFIX }}-win32-x64.tar.gz --verbose rattletrap.exe
        working-directory: rattletrap-${{ github.sha }}-ghc-9.10-windows-2022/artifact
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.PREFIX }}*.tar.gz
            ${{ env.PREFIX }}-schema.json
      - run: cabal upload --publish --username '${{ secrets.HACKAGE_USERNAME }}' --password '${{ secrets.HACKAGE_PASSWORD }}' ${{ env.PREFIX }}.tar.gz
name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  release:
    types:
      - created
  schedule:
    - cron: 0 0 * * 1
